#!/usr/bin/env bash
# Copy the dashboards and alerting files the Helm chart ships into
# charts/chakramcp/files/, from their single source here. Chart CI runs it
# and fails if the result differs from what's committed, so edit the
# sources and re-run this; never edit charts/chakramcp/files/ by hand.
#
#   infra/observability/scripts/sync-chart-assets.sh   (from anywhere)
#
# - Dashboards: Overview (plus a variant without its Loki panel, for a
#   Grafana without Loki) and Logs. Infrastructure stays Compose-only.
# - Alert rules: only those that work on Kubernetes (design §5.3), in two
#   files: rules.yaml, and rules-logs.yaml (the Loki-backed group).
# - The alert message template and the channel files, for the bundled
#   Grafana.
set -euo pipefail

repo=$(cd "$(dirname "$0")/../../.." && pwd)
exec python3 - "$repo" <<'PY'
import json
import os
import shutil
import sys

import yaml

repo = sys.argv[1]
src = os.path.join(repo, "infra/observability/grafana")
out = os.path.join(repo, "charts/chakramcp/files")

# Rules that work on Kubernetes. The others need the Compose exporters or
# the HTTPS probes, and would fire forever without them.
K8S_RULES = {"backend-down", "high-5xx-ratio", "credit-switches-stale", "credit-queue-backlog"}
LOKI_GROUPS = {"logs"}
HEADER = "# Generated by infra/observability/scripts/sync-chart-assets.sh from\n# infra/observability/grafana/{}. Edit the source, then re-run the script.\n"


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def dump_json(doc):
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def dump_yaml(doc, source):
    return HEADER.format(source) + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=1000)


shutil.rmtree(out, ignore_errors=True)

# Dashboards
overview = json.loads(read(os.path.join(src, "dashboards/overview.json")))
write(os.path.join(out, "dashboards/overview.json"), dump_json(overview))
loki_panels = {p["id"] for p in overview["panels"] if (p.get("datasource") or {}).get("uid") == "loki"}
if not loki_panels:
    sys.exit("overview.json has no Loki panel: update this script's variant")
first = min(i for i, p in enumerate(overview["panels"]) if p["id"] in loki_panels)
# The Loki panels sit at the end, under their own row: drop that row too.
cut = first - 1 if overview["panels"][first - 1]["type"] == "row" else first
if any(p["id"] not in loki_panels for p in overview["panels"][first:]):
    sys.exit("overview.json: the Loki panels are no longer last; update this script")
no_loki = dict(overview, panels=overview["panels"][:cut])
write(os.path.join(out, "dashboards/overview-no-loki.json"), dump_json(no_loki))
write(os.path.join(out, "dashboards/logs.json"), dump_json(json.loads(read(os.path.join(src, "dashboards/logs.json")))))

# Alert rules
rules = yaml.safe_load(read(os.path.join(src, "provisioning/alerting/rules.yml")))
found = {r["uid"] for g in rules["groups"] for r in g["rules"]}
missing = (K8S_RULES | {r["uid"] for g in rules["groups"] if g["name"] in LOKI_GROUPS for r in g["rules"]}) - found
if missing:
    sys.exit(f"rules.yml lost {sorted(missing)}: update K8S_RULES")
core, logs = [], []
for group in rules["groups"]:
    if group["name"] in LOKI_GROUPS:
        logs.append(group)
        continue
    kept = [r for r in group["rules"] if r["uid"] in K8S_RULES]
    if kept:
        core.append(dict(group, rules=kept))
write(os.path.join(out, "alerting/rules.yaml"), dump_yaml({"apiVersion": 1, "groups": core}, "provisioning/alerting/rules.yml"))
write(os.path.join(out, "alerting/rules-logs.yaml"), dump_yaml({"apiVersion": 1, "groups": logs}, "provisioning/alerting/rules.yml"))

# The message template and the channels, for the bundled Grafana
shutil.copyfile(os.path.join(src, "provisioning/alerting/templates.yml"), os.path.join(out, "alerting/templates.yaml"))
for name in sorted(os.listdir(os.path.join(src, "channels"))):
    if name.endswith(".yml"):
        write(os.path.join(out, "alerting/channels", name[:-4] + ".yaml"), read(os.path.join(src, "channels", name)))

print(f"synced {out}: 3 dashboards, {sum(len(g['rules']) for g in core)}+{sum(len(g['rules']) for g in logs)} rules, "
      f"{len(os.listdir(os.path.join(out, 'alerting/channels')))} channels")
PY
