apiVersion: v1
kind: Service
metadata:
  name: {{ include "chakramcp.fullname" . }}
  labels:
    {{- include "chakramcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: relay
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "chakramcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: relay
  ports:
    - name: app
      port: {{ .Values.service.appPort }}
      targetPort: app
    - name: relay
      port: {{ .Values.service.relayPort }}
      targetPort: relay
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
    {{- end }}
